package fr.vidal.webservices.interactionservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-10-24T14:35:12.425+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "urn:Vidal", name = "interactionService")
@XmlSeeAlso({ObjectFactory.class})
public interface InteractionService {

    @WebResult(name = "interaction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByInteractionId", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchByInteractionId")
    @WebMethod
    @ResponseWrapper(localName = "searchByInteractionIdResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchByInteractionIdResponse")
    public fr.vidal.webservices.interactionservice.Interaction searchByInteractionId(
        @WebParam(name = "interactionId", targetNamespace = "urn:Vidal")
        java.lang.Integer interactionId
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForProductIds", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForProductIds")
    @WebMethod
    @ResponseWrapper(localName = "searchInteractionCouplesForProductIdsResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForProductIdsResponse")
    public fr.vidal.webservices.interactionservice.InteractionResult searchInteractionCouplesForProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );

    @WebResult(name = "interactionCommonNameGroupResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getInteractionCouplesForCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.GetInteractionCouplesForCommonNameGroupIds")
    @WebMethod
    @ResponseWrapper(localName = "getInteractionCouplesForCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.GetInteractionCouplesForCommonNameGroupIdsResponse")
    public fr.vidal.webservices.interactionservice.InteractionCommonNameGroupResult getInteractionCouplesForCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );

    @WebResult(name = "interactionCommonNameGroupResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForCommonNameGroupId", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForCommonNameGroupId")
    @WebMethod
    @ResponseWrapper(localName = "searchInteractionCouplesForCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForCommonNameGroupIdResponse")
    public fr.vidal.webservices.interactionservice.InteractionCommonNameGroupResult searchInteractionCouplesForCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId,
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForProductId", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForProductId")
    @WebMethod
    @ResponseWrapper(localName = "searchInteractionCouplesForProductIdResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForProductIdResponse")
    public fr.vidal.webservices.interactionservice.InteractionResult searchInteractionCouplesForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId,
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );

    @WebResult(name = "interactionCommonNameGroupResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForCommonNameGroupIds")
    @WebMethod
    @ResponseWrapper(localName = "searchInteractionCouplesForCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.SearchInteractionCouplesForCommonNameGroupIdsResponse")
    public fr.vidal.webservices.interactionservice.InteractionCommonNameGroupResult searchInteractionCouplesForCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getInteractionCouplesForOneProductId", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.GetInteractionCouplesForOneProductId")
    @WebMethod
    @ResponseWrapper(localName = "getInteractionCouplesForOneProductIdResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.GetInteractionCouplesForOneProductIdResponse")
    public fr.vidal.webservices.interactionservice.InteractionResult getInteractionCouplesForOneProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId,
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getInteractionCouplesForProductIds", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.GetInteractionCouplesForProductIds")
    @WebMethod
    @ResponseWrapper(localName = "getInteractionCouplesForProductIdsResponse", targetNamespace = "urn:Vidal", className = "fr.vidal.webservices.interactionservice.GetInteractionCouplesForProductIdsResponse")
    public fr.vidal.webservices.interactionservice.InteractionResult getInteractionCouplesForProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        fr.vidal.webservices.interactionservice.InteractionSeverityType severity
    );
}
